spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    # 뷰 구분을 위해 컨트롤러가 뷰 이름을 반환시 thymeleaf/ 로 시작하면 타임리프로 처리하도록 view-names 지정
#    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    #파일 수정시 반영하려면 하면 재시작을 해줘야 한다. 브라우저 새로고침시 수정사항 반영을 취해 cache=false 설정(운영시 true)
    cache: false
    check-template-location: true
  devtools:
    livereload:
      enabled: true

firebase:
  sdk:
    path: /firebase/serviceAccountKey.json
  hash-config:
    path: /firebase/hashConfig.json
  sample:
    # root : build/resources/main
    path: static/json/goals.json

server:
  port: 1469
logging:
  charset:
    console: UTF-8
  level:
    root: info
    web: info
    